### ISSUE TITLE
Improve the logo

### ISSUE THREAD

**Issue by FJduFou** [DmitriiKh/GPU-Declicker-UWP#3]
Hi,
I am a person who pays great attention to the graphic side, and when I saw the logo, I asked myself: why a screenshot in the logo?
I have made for you a new logo:
I present the result to you, I can make it evolve as you wish if you want, there is in addition the color gradient and the rounding of the corners.
![image](https://user-images.githubusercontent.com/46401854/84267011-b6f6f900-ab25-11ea-8cfb-f028c9a03542.png)

**Comment by DmitriiKh** [comment]
@FJduFou Hi,
Thank you very much for your suggestion. I think this a good idea.

I wonder if it looks okay with parentheses? Something like this:

![image](https://user-images.githubusercontent.com/31587652/84262889-d0cc1800-aaf4-11ea-9448-fddbdf63422b.png)

What do you think?

**Comment by FJduFou** [comment]
The problem is in parentheses or you want me to add parentheses?
